fixtures:
  forge_modules:
    apt: "puppetlabs/apt"
    concat: "puppetlabs/concat"
    cron_core: "puppetlabs/cron_core"
    mcollective: "choria/mcollective"
    mcollective_choria: "choria/mcollective_choria"
    mcollective_agent_puppet: "choria/mcollective_agent_puppet"
    mcollective_agent_package: "choria/mcollective_agent_package"
    mcollective_agent_service: "choria/mcollective_agent_service"
    mcollective_agent_filemgr: "choria/mcollective_agent_filemgr"
    mcollective_util_actionpolicy: "choria/mcollective_util_actionpolicy"
    scheduled_task: "puppetlabs/scheduled_task"
    stdlib: "puppetlabs/stdlib"
    yumrepo_core: "puppetlabs/yumrepo_core"
    sysemd: "puppet/systemd"
